apiVersion: v1
kind: ConfigMap
metadata:
  name: app-properties
data:
  #General properties
  spring.kafka.bootstrap-servers: amq-kafka-bootstrap.automation-kafka.svc.cluster.local:9093
  spring.kafka.security.protocol: SASL_SSL 
  spring.kafka.enable.ssl.certificate.verification: 'false'

  # Consumer properties
  spring.kafka.consumer.properties.sasl.mechanism: SCRAM-SHA-512
  spring.kafka.consumer.ssl.trust-store-location: file:/tmp/amq/truststore.jks
  spring.kafka.consumer.ssl.trust-store-password: password
  spring.kafka.consumer.ssl.trust-store-type: PKCS12
  spring.kafka.consumer.properties.sasl.jaas.config: |
    org.apache.kafka.common.security.scram.ScramLoginModule required username: "admin" password: "RKZURlH6hpzo";
  spring.kafka.consumer.group-id: springboot
  spring.kafka.consumer.auto-offset-reset: earliest
  spring.kafka.consumer.key-deserializer: 
    org.apache.kafka.common.serialization.StringDeserializer
  spring.kafka.consumer.value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  spring.kafka.consumer.properties.spring.json.trusted.packages: com.laboratory.domain

  # Producer properties
  spring.kafka.producer.properties.sasl.mechanism: SCRAM-SHA-512
  spring.kafka.producer.ssl.trust-store-location: file:/tmp/amq/truststore.jks
  spring.kafka.producer.ssl.trust-store-password: password
  spring.kafka.producer.ssl.trust-store-type: PKCS12
  spring.kafka.producer.properties.sasl.jaas.config: |
    org.apache.kafka.common.security.scram.ScramLoginModule required username: "admin" password: "RKZURlH6hpzo";
  spring.kafka.producer.key-serializer: |
    org.apache.kafka.common.serialization.StringSerializer
  spring.kafka.producer.value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  #spring.kafka.
  topic.name.consumer: marvel
  topic.name.producer: marvel

  # Common Kafka Properties
  auto.create.topics.enable: 'false'
